import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import CopyRight from "@/components/CopyRight";
import Nav from "@/components/Nav";
import Header from "@/components/Header";
import { dbConnect } from "@/service/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Nav />
        <div style={{ minHeight: `calc(100vh - 583.42px)` }}>{children}</div>
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
